function param = getQuantizers(param)

% Get quantizers
reUseLUT = zeros(1,param.maxIter);
qmode = 'maxMIsym';
cnmethod = 'minsum';
vnmethod = 'tree'; 
useDecNode = 1;

SNRlin = 10^(param.designSNR/10);
sigma2 = 1/(2*SNRlin*param.R);


[ ~, param.QVN, MI] = decoderDesignBIAWGN(  [2^param.QLLR*ones(1,param.maxIter) 2], ...
                                            2^param.QCh, ...
                                            reUseLUT, ...
                                            param.VNodeDegree, ...
                                            param.CNodeDegree, ...
                                            -10*log10(sigma2), ...
                                            param.maxIter, ...
                                            qmode, cnmethod, ...
                                            vnmethod, ...
                                            param.cnroot, ...
                                            param.vnroot, ...
                                            param.decroot, ...
                                            useDecNode);